FILE_NAME = 'DataFrame.csv'
RAW_DATA_FILE_PATH = 'artifacts\DataFrame.csv'
DATA_FOLDER_PATH = 'artifacts'
CLEAN_DATA_FILE_PATH = 'artifacts\Cleaned_df.csv'
xTRAIN_DATA_FILE_PATH = 'artifacts\X_train.csv'
xTEST_DATA_FILE_PATH = 'artifacts\X_test.csv'
yTRAIN_DATA_FILE_PATH = 'artifacts\Y_train.csv'
yTEST_DATA_FILE_PATH = 'artifacts\Y_test.csv'
TRANSFORM_xTRAIN_DATA_FILE_PATH = 'artifacts\TRANSFORMED_X_train.csv'
TRANSFORM_xTEST_DATA_FILE_PATH = 'artifacts\TRANSFORMED_X_test.csv'
TARGET_FEATURE = 'math score'
RESULT_IMG_FOLDER_PATH = 'artifacts\Results\img'
RESULT_DATA_FOLDER_PATH = 'artifacts\Results\data'

P_VALUE = 0.00000001